// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    public partial class MyContextModel
    {
        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var product = ProductEntityType.Create(this);

            CategoryEntityType.CreateAnnotations(category);
            ProductEntityType.CreateAnnotations(product);

            AddAnnotation("ProductVersion", "6.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
